### ISSUE TITLE
To-Do lists before publishing v1.0.0

### ISSUE THREAD

**Issue by Maples7** [Maples7/barn#1]
- [x] Refactor code & make things more componentized
- [x] Make default theme better to add flexible options about some unimportant fields
- [x] ~Add bash-completion shortcuts for commands and options~

_What‘re your needs? Let's discuss below._

:smiley:
